#! /usr/bin/env php

<?php

use Acme\ShowCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

require 'vendor/autoload.php';

$app = new Application('MoviePedia', '1.0');

$app->add(new ShowCommand);

$app->run();